[package]
name = "api"
version = "0.1.0"
authors = ["Rust Bicycle Book <bicycle-book@example.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

